---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dmbc
  labels:
    app: dmbc
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-GeoIP-Country $geoip_country_code;
      proxy_set_header X-GeoIP-Country-Name $geoip_country_name;
      proxy_set_header X-GeoIP-Region-Name $geoip_region_name;
      proxy_set_header X-GeoIP-City $geoip_city;
      proxy_set_header X-GeoIP-Postal-Code $geoip_postal_code;
      proxy_set_header CF-IPCountry $http_cf_ipcountry;
      more_set_headers "X-XSS-Protection: 1; mode=block";
      more_set_headers "X-Frame-Options: SAMEORIGIN";
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers:
      Content-Type, Accept, Authorization,
      Language, X-Forwarded-For, Set-Cookie, Payment-Session-Id, Access-Control-Allow-Origin
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, OPTIONS, PUT, DELETE
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: 92.60.189.125,212.90.166.94,94.176.196.244,34.90.237.96,35.189.83.42,35.233.1.160,104.199.34.31,35.233.1.160,34.76.42.79,93.74.83.220,185.143.147.206
spec:
  rules:
  - host: dm-blockchain-dev02.devss.xyz
    http:
      paths:
      - backend:
          serviceName: dmbc
          servicePort: 8000
        path: /  
  tls:
  - hosts:
    - dm-bc01-dev02.devss.xyz
    secretName: devss-tls   