[api]
current_node = "node0"
address = "0.0.0.0:8000"
private_address = "0.0.0.0:8001"
peer_address = "0.0.0.0:2000"
peers = []
keys_path = "./var/keys"

[db]
path = "./var/db"

[nats]
addresses = ["nats://nats:4222"]
